# Generated by Django 2.2.4 on 2019-11-30 19:56

from django.db import migrations

def autocomplete_new_building(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for house in Flat.objects.all():
        house.new_building = None
        house.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(autocomplete_new_building, move_backward)
    ]
