# Generated by Django 2.2.4 on 2019-12-01 18:38

from django.db import migrations
import phonenumbers


def filling_owner_phone_pure(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for phone in Flat.objects.all():
        parsed_phone_number = phonenumbers.parse(phone.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_phone_number):
            phone.owner_phone_pure = phonenumbers.format_number(parsed_phone_number, phonenumbers.PhoneNumberFormat.E164)
            phone.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for phone in Flat.objects.all():
        phone.owner_phone_pure = ""
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(filling_owner_phone_pure, move_backward)
    ]
