# Generated by Django 2.2.4 on 2019-12-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    def connect_flats_to_owners(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        Owner = apps.get_model('property', 'Owner')
        for owner in Owner.objects.all():
            print(owner)
            flats = Flat.objects.filter(owner=owner.owner)
            owner.owner_flats.add(*[flats])

    dependencies = [
        ('property', '0011_auto_20191202_1746'),
    ]

    operations = [
        migrations.RunPython(connect_flats_to_owners)
    ]
